<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * =========================================================================
 * SEEDER ARTICLE - SEEDER ARTIKEL HELPDESK
 * =========================================================================
 *
 * Seeder ini membuat artikel sample untuk sistem helpdesk.
 *
 * Struktur Artikel:
 * - Setiap artikel EXPLICITLY assigned ke kategori yang benar
 * - Domain-specific titles dan content (tidak ada generic wording)
 * - Clear keyword separation antar domain
 * - Balanced article count per category (5-8 artikel per kategori)
 * - Domain keamanan diisolasi dengan artikel dedicated
 * - Tidak ada overlapping topics antar kategori
 *
 * Kategori dan Jumlah Artikel:
 * - Wifi & Jaringan: 6 artikel
 * - Komputer: 7 artikel
 * - Printer: 6 artikel
 * - Email: 6 artikel
 * - Keamanan Sistem: 8 artikel
 * - Aplikasi: 6 artikel
 */
class ArticleSeeder extends Seeder
{
    /**
     * Fungsi:
     * Menjalankan seeder untuk membuat artikel sample.
     */
    public function run(): void
    {
        // Get categories by name for explicit assignment
        $wifiJaringan = Category::where('name', 'Wifi & Jaringan')->first();
        $komputer = Category::where('name', 'Komputer')->first();
        $printer = Category::where('name', 'Printer')->first();
        $email = Category::where('name', 'Email')->first();
        $keamananSistem = Category::where('name', 'Keamanan Sistem')->first();
        $aplikasi = Category::where('name', 'Aplikasi')->first();

        // Get staff users for assignment
        $staffs = User::where('role', 'staff')->get();
        if ($staffs->isEmpty()) {
            $staffs = User::where('role', 'admin')->get();
        }

        // ============================================================
        // WIFI & JARINGAN (6 articles)
        // Domain: Network connectivity, wifi, router, internet connection
        // ============================================================
        $wifiArticles = [
            [
                "title" => "Cara Mengatasi Wifi Tidak Terhubung ke Perangkat",
                "content" => "Permasalahan WiFi yang tidak bisa terhubung (unable to connect) pada perangkat seperti laptop atau smartphone seringkali disebabkan oleh kegagalan negosiasi IP address, konfigurasi nirkabel yang salah, atau masalah pada firmware router. Berikut adalah panduan langkah demi langkah untuk mengatasinya secara tuntas:\n\n1. **Melakukan Power Cycle (Mereset Daya) Router**\nLangkah pertama yang paling sederhana namun sangat efektif adalah merestart router. Cabut adaptor daya router dari stopkontak, tunggu sekitar 30 detik agar sisa daya di kapasitor habis, kemudian colokkan kembali. Tunggu hingga semua lampu indikator (Power, DSL/PON, WLAN, dan Internet) menyala stabil.\n\n2. **Melupakan Jaringan (Forget Network) dan Re-koneksi**\nKadang kala data konfigurasi jaringan yang tersimpan di perangkat Anda korup atau tidak sinkron setelah adanya perubahan password. Masuk ke pengaturan WiFi di perangkat Anda, pilih nama WiFi (SSID) yang bermasalah, lalu ketuk 'Forget Network' atau 'Lupakan Jaringan'. Setelah itu, aktifkan ulang WiFi di perangkat Anda, pilih kembali nama WiFi tersebut, dan masukkan password dengan benar.\n\n3. **Memeriksa Batas Kapasitas DHCP Server**\nJika perangkat menampilkan status 'Obtaining IP Address...' dalam waktu lama, kemungkinan pool IP address pada DHCP server di router Anda sudah penuh. Anda perlu masuk ke halaman administrasi router (biasanya di alamat 192.168.1.1 atau 192.168.0.1) dan memperluas range DHCP IP Address, atau mengurangi durasi DHCP Lease Time agar IP address yang tidak aktif segera dilepaskan.\n\n4. **Menonaktifkan MAC Address Filtering**\nBeberapa router kantor dikonfigurasi dengan fitur keamanan MAC Filtering untuk mencegah perangkat asing terhubung. Pastikan MAC Address perangkat Anda sudah didaftarkan (whitelisted) oleh administrator jaringan di pengaturan router.\n\n5. **Memperbarui Driver Network Adapter di PC/Laptop**\nUntuk pengguna laptop Windows, driver kartu WiFi yang usang dapat menyebabkan kegagalan koneksi. Buka Device Manager -> Network adapters -> Klik kanan pada kartu WiFi Anda -> pilih Update driver.",
                "excerpt" => "Panduan lengkap mengatasi masalah wifi yang tidak terhubung ke perangkat Anda.",
                "keywords" => "wifi tidak terhubung, router wifi, signal wifi, restart router, MAC address filtering, jaringan wireless",
                'category_id' => $wifiJaringan->id,
            ],
            [
                "title" => "Solusi Internet Lambat pada Jaringan Wifi Kantor",
                "content" => "Koneksi internet lambat pada jaringan nirkabel kantor adalah keluhan yang sangat umum dan dapat menurunkan efisiensi kerja. Masalah ini umumnya terjadi akibat manajemen bandwidth yang kurang optimal atau kendala infrastruktur fisik. Ikuti langkah-langkah optimasi berikut untuk mengatasi internet lambat:\n\n1. **Migrasi Frekuensi dari 2.4 GHz ke 5 GHz**\nPita frekuensi 2.4 GHz sangat rentan terhadap interferensi dari perangkat lain seperti microwave, bluetooth, dan sinyal WiFi tetangga. Frekuensi 5 GHz menawarkan bandwidth yang jauh lebih besar dan saluran (channels) yang tidak saling tumpang tindih. Pastikan access point dan perangkat karyawan sudah mendukung dan terhubung ke pita frekuensi 5 GHz.\n\n2. **Penerapan QoS (Quality of Service) pada Router**\nTanpa QoS, satu pengguna yang melakukan download file besar atau streaming video berkualitas tinggi dapat menghabiskan seluruh bandwidth kantor. Konfigurasikan QoS pada router utama untuk memprioritaskan lalu lintas web penting (seperti aplikasi email kantor, video conference Zoom/Meet, dan akses server data internal) di atas lalu lintas non-pekerjaan.\n\n3. **Membatasi Jumlah Perangkat (Device Density) Per Access Point**\nAccess point kelas rumahan biasanya hanya mampu menangani 10-15 perangkat secara bersamaan sebelum kinerjanya menurun drastis. Untuk lingkungan kantor, gunakan Access Point kelas Enterprise yang dirancang khusus untuk menangani 50 hingga 100 koneksi bersamaan tanpa degradasi performa.\n\n4. **Melakukan Site Survey untuk Penempatan Access Point**\nPastikan access point diletakkan di area terbuka yang tinggi, bebas dari penghalang fisik tebal seperti tembok beton atau lemari besi. Sinyal WiFi melemah secara eksponensial ketika harus menembus dinding tebal.\n\n5. **Gunakan Sambungan Kabel LAN untuk Perangkat Kritis**\nPerangkat yang membutuhkan koneksi sangat stabil dan cepat (seperti PC Server, Smart TV di ruang meeting utama, atau komputer desainer) sebaiknya dihubungkan menggunakan kabel LAN Cat6 langsung ke switch, bukan melalui WiFi.",
                "excerpt" => "Tips mengatasi internet lambat khusus untuk jaringan wifi kantor.",
                "keywords" => "internet lambat, bandwidth kantor, QoS router, access point, frekuensi 5GHz, ISP",
                'category_id' => $wifiJaringan->id,
            ],
            [
                "title" => "Cara Reset Router dan Konfigurasi Ulang Jaringan",
                "content" => "Reset router ke pengaturan pabrik (factory reset) adalah langkah terakhir yang diambil ketika router mengalami error sistem yang parah, lupa password administrasi, atau setelah serangan malware pada jaringan. Berikut panduan lengkap untuk melakukan reset dan konfigurasi ulang:\n\n1. **Melakukan Hard Reset Fisik**\nPastikan router dalam keadaan menyala. Cari tombol reset kecil yang berada di bagian belakang atau bawah unit router. Tombol ini biasanya berada di dalam lubang kecil untuk menghindari penekanan tidak sengaja. Masukkan ujung paperclip atau jarum ke dalam lubang tersebut, tekan dan tahan tombol reset selama 10 hingga 15 detik. Lepaskan tombol ketika semua lampu indikator LED berkedip secara bersamaan, menandakan proses reboot pabrik dimulai.\n\n2. **Mengakses Halaman Konfigurasi Default**\nHubungkan laptop Anda ke router menggunakan kabel LAN pada salah satu port LAN (bukan port WAN/Internet). Buka web browser dan ketikkan alamat IP gateway default router (biasanya tertera pada stiker di bagian bawah router, seperti `192.168.1.1`, `192.168.0.1`, atau `192.168.100.1`). Masukkan username and password default yang tertera (biasanya `admin` / `admin`).\n\n3. **Mengonfigurasi Koneksi WAN (Internet)**\nMasuk ke menu Network -> WAN. Pilih tipe koneksi internet sesuai dengan ketentuan ISP Anda. Kebanyakan koneksi kantor menggunakan IP Statis (Static IP) atau PPPoE. Masukkan IP Address, Subnet Mask, Gateway, dan DNS Server yang diberikan oleh ISP Anda.\n\n4. **Menyiapkan Nama WiFi (SSID) dan Enkripsi Keamanan**\nMasuk ke menu Wireless Settings. Tentukan Nama WiFi (SSID) baru untuk kantor Anda. Pilih tipe keamanan nirkabel yang kuat, sangat disarankan menggunakan **WPA2-PSK [AES]** atau **WPA3**. Buat password WiFi baru yang terdiri dari minimal 12 karakter dengan kombinasi huruf besar, huruf kecil, angka, dan simbol.\n\n5. **Mengubah Kredensial Administrator Router**\nIni adalah langkah keamanan krusial yang sering terlewat. Masuk ke menu System Tools -> Modify Password. Ubah username dan password default admin menjadi sesuatu yang unik agar pihak luar tidak bisa mengakses konfigurasi router Anda secara ilegal.",
                "excerpt" => "Panduan reset router ke pengaturan pabrik dan konfigurasi ulang.",
                "keywords" => "reset router, konfigurasi router, admin router, 192.168.1.1, SSID, password default",
                'category_id' => $wifiJaringan->id,
            ],
            [
                "title" => "Mengatasi Wifi Sering Putus Nyambung pada Jaringan Kantor",
                "content" => "WiFi yang tidak stabil dan sering terputus-putus sangat mengganggu kelancaran pekerjaan. Masalah ini biasanya bersumber dari interferensi saluran, jangkauan sinyal yang kurang merata, atau masalah pada firmware access point. Berikut cara mengatasinya:\n\n1. **Memilih Saluran (Channel) yang Tepat**\nPada frekuensi 2.4 GHz, hanya ada tiga saluran yang tidak saling tumpang tindih (non-overlapping channels), yaitu **1, 6, dan 11**. Gunakan aplikasi WiFi Analyzer untuk memindai jaringan di sekitar Anda, lalu ubah konfigurasi saluran router ke saluran yang paling sedikit digunakan oleh jaringan tetangga.\n\n2. **Mengatasi Overheating pada Router/Access Point**\nPerangkat jaringan yang menyala terus-menerus selama 24 jam sehari dapat mengalami overheating (panas berlebih), terutama jika diletakkan di tempat tertutup tanpa ventilasi udara yang baik. Hal ini akan menyebabkan router sering crash atau merestart chip nirkabelnya sendiri secara periodik. Pastikan router diletakkan di ruangan ber-AC atau area dengan sirkulasi udara yang baik.\n\n3. **Menerapkan Teknologi Mesh WiFi atau WiFi Extender**\nJika ada beberapa ruangan kantor yang mengalami 'dead zone' atau sinyal sangat lemah (hanya 1-2 bar), sinyal perangkat di ruangan tersebut akan sering terputus. Tambahkan node Mesh WiFi atau access point tambahan yang dihubungkan dengan kabel LAN backhaul untuk memperluas jangkauan nirkabel tanpa mengorbankan kecepatan.\n\n4. **Memperbarui Firmware Perangkat Access Point**\nBug pada sistem operasi router seringkali menjadi penyebab drop koneksi secara acak. Masuk ke situs resmi produsen perangkat (seperti TP-Link, Ubiquiti, Mikrotik, atau Cisco), download firmware versi terbaru yang stabil, dan upload melalui admin panel router Anda.",
                "excerpt" => "Solusi wifi tidak stabil yang sering terputus di lingkungan kantor.",
                "keywords" => "wifi putus nyambung, interferensi channel, wifi extender, mesh network, firmware router, access point enterprise",
                'category_id' => $wifiJaringan->id,
            ],
            [
                "title" => "Cara Mengamankan Jaringan Wifi dari Akses Tidak Sah",
                "content" => "Mengamankan jaringan nirkabel kantor adalah kewajiban mutlak demi menjaga keamanan data sensitif perusahaan dan mencegah eksploitasi jaringan oleh pihak luar. Berikut langkah-langkah praktis untuk memperketat keamanan WiFi kantor Anda:\n\n1. **Hindari Enkripsi Lemah dan Gunakan WPA3 / WPA2-Enterprise**\nJangan pernah menggunakan enkripsi WEP atau WPA standar yang sudah sangat usang dan mudah diretas dalam hitungan menit menggunakan tools gratis. Gunakan minimal **WPA2-PSK [AES]** atau tingkatkan ke **WPA3** jika perangkat mendukung. Untuk skala kantor menengah ke atas, gunakan **WPA2/WPA3 Enterprise (802.1X)** yang mengautentikasi setiap pengguna menggunakan kredensial individual (username dan password unik dari Active Directory/LDAP), bukan satu password WiFi yang sama untuk semua orang.\n\n2. **Pisahkan Jaringan untuk Karyawan dan Guest (VLAN)**\nJangan biarkan tamu atau pihak eksternal kantor menggunakan jaringan yang sama dengan komputer kerja internal yang menyimpan database sensitif. Aktifkan fitur Guest Network atau gunakan **VLAN (Virtual Local Area Network)** pada router dan switch Anda untuk mengisolasi traffic pengunjung agar tidak dapat mengakses server internal perusahaan.\n\n3. **Menyembunyikan SSID (Disable SSID Broadcast)**\nDengan menonaktifkan siaran nama WiFi (SSID Broadcast), WiFi kantor Anda tidak akan terlihat di daftar perangkat nirkabel biasa. Pengguna harus memasukkan nama WiFi secara manual dan persis untuk bisa terhubung. Meskipun langkah ini bukan perlindungan mutlak, ini membantu mengurangi upaya scanning acak dari luar gedung.\n\n4. **Mengaktifkan Fitur MAC Address Filtering**\nBatasi akses WiFi hanya untuk perangkat resmi milik perusahaan (laptop dan smartphone operasional). Daftarkan MAC Address (ID fisik kartu jaringan) dari masing-masing perangkat tersebut ke dalam whitelist router. Semua perangkat lain yang mencoba terhubung, meskipun mengetahui password WiFi, akan ditolak secara otomatis.",
                "excerpt" => "Strategi pengamanan jaringan wifi perusahaan dari akses tidak sah.",
                "keywords" => "keamanan wifi, enkripsi WPA3, WPA2-AES, MAC address filtering, hide SSID, VLAN, network guest",
                'category_id' => $wifiJaringan->id,
            ],
            [
                "title" => "Troubleshooting Koneksi Internet Putus Nyambung dari ISP",
                "content" => "Koneksi internet yang tidak stabil dan sering terputus langsung dari provider ISP (Internet Service Provider) memerlukan diagnosis sistematis untuk membedakan apakah masalah terjadi di jaringan lokal kantor atau pada jaringan fiber optik milik ISP. Ikuti langkah diagnosis berikut:\n\n1. **Menganalisis Lampu Indikator pada Modem/ONT**\nModem fiber optik memiliki lampu indikator status koneksi yang sangat penting. Periksa lampu berlabel **LOS** (Loss of Signal) dan **PON** (Passive Optical Network). Jika lampu **LOS berkedip merah** atau **PON mati**, ini berarti kabel fiber optik dari tiang jalan ke kantor Anda terputus atau mengalami redaman sinyal yang sangat tinggi. Masalah ini hanya bisa diselesaikan oleh teknisi lapangan ISP.\n\n2. **Melakukan Uji Bypass Koneksi Langsung**\nUntuk memastikan masalah tidak disebabkan oleh router internal kantor atau switch, lepaskan kabel LAN yang menghubungkan modem ISP ke router Anda. Hubungkan satu laptop langsung ke port LAN-1 pada modem ISP menggunakan kabel ethernet. Jika internet lancar saat terhubung langsung ke modem tetapi putus saat melewati router, maka masalahnya terletak pada router Anda.\n\n3. **Menjalankan Perintah Continuous Ping**\nBuka Command Prompt (Windows) atau Terminal (Mac/Linux), kemudian ketikkan perintah `ping 8.8.8.8 -t`. Perhatikan outputnya secara berkala. Jika muncul banyak tulisan 'Request Timed Out' (RTO) diiringi dengan nilai 'time' yang melonjak tinggi (di atas 100ms), maka jalur koneksi Anda sedang mengalami packet loss atau kemacetan trafik yang parah di tingkat gateway ISP.\n\n4. **Menghubungi Call Center Provider ISP**\nApabila hasil diagnosis mengarah ke masalah ISP, catat nomor pelanggan Anda dan segera hubungi layanan pelanggan ISP (seperti IndiHome, Biznet, Astinet, dll.). Laporkan status lampu indikator modem dan hasil test ping Anda untuk mempercepat pembuatan tiket perbaikan dan penjadwalan kunjungan teknisi.",
                "excerpt" => "Cara mendiagnosis dan mengatasi masalah koneksi internet dari provider ISP.",
                "keywords" => "internet putus, ISP gangguan, modem indicator, fiber optic, call center ISP, restart modem",
                'category_id' => $wifiJaringan->id,
            ],
        ];

        // ============================================================
        // KOMPUTER (7 articles)
        // Domain: PC, laptop, performa, hardware komputer, OS
        // ============================================================
        $komputerArticles = [
            [
                "title" => "Cara Mengatasi PC/Laptop Lemot dengan Optimasi Sistem",
                "content" => "Kinerja PC atau laptop Windows yang lambat atau sering mengalami hang/freeze sangat memengaruhi produktivitas harian. Sebelum memutuskan untuk membeli perangkat baru, Anda dapat mengoptimalkan sistem operasi Windows Anda dengan langkah-langkah komprehensif berikut:\n\n1. **Mematikan Startup Programs yang Tidak Penting**\nBanyak aplikasi yang otomatis berjalan di latar belakang saat komputer pertama kali dinyalakan. Ini memperlambat proses booting dan memakan memori RAM. Tekan `Ctrl + Shift + Esc` untuk membuka Task Manager, pergi ke tab **Startup** (atau Startup Apps), lalu disable aplikasi non-sistem yang tidak Anda butuhkan segera (seperti Spotify, Steam, atau pembaca PDF).\n\n2. **Membersihkan File Sampah Menggunakan Disk Cleanup**\nWindows menyimpan file instalasi lama, cache update, dan file temporary yang menumpuk seiring waktu. Tekan tombol Windows, ketik **Disk Cleanup**, pilih drive C:, lalu centang opsi seperti 'Temporary Files', 'Windows Update Cleanup', dan 'Recycle Bin'. Klik OK untuk menghapus file-file tersebut dengan aman.\n\n3. **Menonaktifkan Efek Visual Windows**\nEfek animasi transisi dan bayangan jendela mengonsumsi resource GPU dan CPU yang cukup besar pada komputer berspesifikasi rendah. Masuk ke Settings -> System -> About -> **Advanced system settings**. Pada bagian Performance, klik Settings. Pilih opsi **Adjust for best performance**, lalu klik Apply.\n\n4. **Melakukan Upgrade Hardware (RAM dan SSD)**\nJika komputer Anda masih menggunakan Hard Disk Drive (HDD) sebagai drive utama sistem operasi, ini adalah bottleneck terbesar. Mengganti HDD utama ke **Solid State Drive (SSD)** akan memberikan peningkatan kecepatan booting dan loading aplikasi hingga 10 kali lipat. Selain itu, pastikan RAM komputer Anda minimal 8GB untuk kebutuhan aplikasi perkantoran modern.",
                "excerpt" => "Panduan lengkap optimasi PC/laptop agar tidak lemot dan lebih responsif.",
                "keywords" => "PC lemot, laptop lemot, optimasi Windows, startup programs, upgrade RAM, SSD, Disk Cleanup",
                'category_id' => $komputer->id,
            ],
            [
                "title" => "Cara Mengganti Thermal Paste CPU dan GPU Laptop",
                "content" => "Overheating pada laptop yang ditandai dengan kipas berputar sangat kencang dan performa melambat (thermal throttling) biasanya disebabkan oleh thermal paste yang sudah kering dan mengeras. Thermal paste berfungsi untuk mengisi rongga udara mikro antara permukaan prosesor (CPU/GPU) dengan heatsink logam agar transfer panas berjalan maksimal. Berikut panduan penggantian thermal paste:\n\n1. **Mempersiapkan Alat dan Bahan**\nSiapkan obeng presisi sesuai dengan sekrup laptop Anda, thermal paste berkualitas tinggi (seperti Arctic MX-4, Noctua NT-H1, atau Thermal Grizzly), tissue kering bebas serat (microfiber), dan cairan **Isopropyl Alcohol (IPA)** dengan kadar minimal 90%.\n\n2. **Membongkar Casing dan Melepas Baterai**\nMatikan laptop sepenuhnya dan cabut charger. Buka casing belakang laptop secara perlahan. Langkah pertama setelah casing terbuka adalah **mencabut konektor baterai utama** dari motherboard untuk menghindari risiko korsleting (short circuit) akibat sentuhan obeng.\n\n3. **Melepas Heatsink dan Kipas**\nLepaskan sekrup yang menahan heatsink di atas CPU dan GPU. Lepaskan sekrup sesuai dengan urutan angka yang tertera di dekat sekrup (biasanya 1, 2, 3, 4) untuk mencegah tekanan melengkung pada silikon prosesor. Angkat heatsink secara perlahan.\n\n4. **Membersihkan Thermal Paste Lama**\nBasahi tissue dengan cairan Isopropyl Alcohol, lalu bersihkan sisa thermal paste yang mengeras di permukaan CPU, GPU, dan dasar heatsink hingga benar-benar bersih dan mengkilap.\n\n5. **Mengaplikasikan Thermal Paste Baru**\nOleskan thermal paste baru di tengah-tengah core CPU dan GPU sebesar biji kacang polong. Jangan terlalu banyak karena paste yang meluber ke motherboard dapat menyebabkan gangguan (meskipun non-konduktif, meluber menghambat pendinginan optimal). Pasang kembali heatsink, kencangkan sekrup secara diagonal sesuai urutan angka, pasang konektor baterai, dan rakit kembali laptop Anda.",
                "excerpt" => "Panduan mengganti thermal paste untuk mengatasi laptop overheating.",
                "keywords" => "thermal paste, laptop overheating, CPU temperature, GPU temperature, heatsink, HWMonitor",
                'category_id' => $komputer->id,
            ],
            [
                "title" => "Solusi Blue Screen of Death (BSOD) pada Windows",
                "content" => "Layar biru atau *Blue Screen of Death* (BSOD) adalah mekanisme pertahanan sistem operasi Windows ketika mendeteksi kesalahan fatal yang tidak dapat dipulihkan secara aman, guna mencegah kerusakan perangkat keras atau kehilangan data lebih lanjut. Berikut adalah panduan sistematis untuk mendiagnosis dan mengatasi masalah BSOD:\n\n1. **Mencatat Kode Error (Stop Code)**\nSaat layar biru muncul, perhatikan bagian bawah layar. Catat kode error yang ditampilkan, misalnya `DPC_WATCHDOG_VIOLATION`, `PAGE_FAULT_IN_NONPAGED_AREA`, atau `SYSTEM_SERVICE_EXCEPTION`. Kode ini sangat berguna untuk mencari solusi spesifik di internet.\n\n2. **Menjalankan Windows Memory Diagnostic**\nRAM yang rusak atau tidak stabil merupakan penyebab paling sering dari crash BSOD acak. Tekan tombol `Win + R`, ketik `mdsched.exe`, lalu pilih **Restart now and check for problems**. Komputer akan merestart dan melakukan pengujian memori secara mendalam. Jika ditemukan error, Anda harus mengganti modul RAM yang rusak.\n\n3. **Memeriksa Integritas File Sistem (SFC & DISM)**\nKerusakan file sistem Windows dapat diperbaiki menggunakan command prompt bawaan. Buka Command Prompt sebagai Administrator, ketik perintah `sfc /scannow` lalu tekan Enter. Jika proses selesai, jalankan perintah lanjutan: `DISM /Online /Cleanup-Image /RestoreHealth` untuk memperbaiki citra sistem Windows.\n\n4. **Melakukan Rollback atau Update Driver Baru**\nJika BSOD mulai terjadi setelah Anda mengunduh driver baru (seperti driver kartu grafis/VGA atau network adapter), buka Device Manager, klik kanan pada perangkat terkait, pilih Properties -> tab Driver -> klik **Rollback Driver** untuk kembali ke versi stabil sebelumnya.",
                "excerpt" => "Cara mengatasi error Blue Screen of Death di Windows dengan langkah lengkap.",
                "keywords" => "BSOD, blue screen, error code Windows, Memory Diagnostic, chkdsk, driver bermasalah, Safe Mode",
                'category_id' => $komputer->id,
            ],
            [
                "title" => "Cara Upgrade RAM dan SSD pada Laptop/Komputer",
                "content" => "Meng-upgrade RAM (Random Access Memory) dan beralih dari Hard Disk Drive (HDD) ke Solid State Drive (SSD) adalah cara paling hemat biaya untuk menghidupkan kembali komputer lama tanpa perlu membeli unit baru. Berikut panduan praktis untuk melakukan upgrade ini:\n\n1. **Memastikan Kompatibilitas Hardware**\nSebelum membeli komponen baru, periksa spesifikasi motherboard Anda. Cari tahu jenis RAM yang didukung (misalnya DDR3, DDR4, atau DDR5), frekuensi maksimalnya (misalnya 2666MHz atau 3200MHz), serta jenis slot SSD yang tersedia (apakah SATA 2.5 inci, M.2 SATA, atau M.2 NVMe PCIe).\n\n2. **Prosedur Pemasangan RAM Baru**\nMatikan PC/laptop dan cabut semua kabel daya. Untuk laptop, cabut konektor baterai. Cari slot RAM pada motherboard. Jika memasang RAM tambahan (untuk konfigurasi dual-channel), sejajarkan takik pada modul RAM dengan tonjolan di slot, masukkan dengan sudut 45 derajat, lalu tekan ke bawah hingga pengunci plastik di kedua ujungnya berbunyi klik.\n\n3. **Prosedur Migrasi dan Pemasangan SSD**\nJika Anda ingin memindahkan sistem operasi tanpa menginstal ulang dari awal, hubungkan SSD baru ke komputer (bisa menggunakan enclosure USB) dan gunakan software cloning gratis seperti **Macrium Reflect** atau **Acronis** untuk menyalin seluruh partisi drive C: lama ke SSD baru. Setelah proses kloning selesai, pasang SSD baru ke dalam slot internal komputer.\n\n4. **Penyesuaian Boot Priority di BIOS/UEFI**\nNyalakan komputer dan tekan tombol BIOS (biasanya F2, F12, atau Delete). Masuk ke menu **Boot Options** dan ubah urutan boot (boot order) agar SSD baru berada di urutan pertama (Boot Priority #1). Simpan pengaturan dan restart.",
                "excerpt" => "Panduan upgrade RAM dan SSD untuk meningkatkan performa komputer.",
                "keywords" => "upgrade RAM, upgrade SSD, DDR4, dual channel, clone HDD, Macrium Reflect, BIOS boot order",
                'category_id' => $komputer->id,
            ],
            [
                "title" => "Mengatasi Laptop Overheating dan Fan Berisik",
                "content" => "Laptop yang cepat panas (overheat) hingga mati sendiri secara mendadak merupakan indikasi bahwa sistem pendingin laptop Anda tidak mampu membuang panas dari komponen internal dengan efisien. Kipas yang berputar sangat kencang dan berisik adalah usaha sistem untuk menurunkan suhu. Berikut cara mengatasi masalah tersebut:\n\n1. **Membersihkan Ventilasi dan Kipas dari Debu**\nSeiring waktu, debu halus akan menumpuk di sirip-sirip heatsink logam dan bilah kipas laptop, menghalangi aliran udara keluar. Matikan laptop, gunakan kaleng udara bertekanan (*compressed air*) untuk meniup debu keluar dari ventilasi udara bawah dan samping. Jika memungkinkan, buka casing bawah dan bersihkan kipas secara manual menggunakan kuas halus.\n\n2. **Hindari Menggunakan Laptop di Permukaan Empuk**\nJangan pernah meletakkan laptop yang sedang menyala di atas kasur, sofa, karpet, atau pangkuan Anda. Bahan empuk tersebut akan menutup lubang ventilasi masuk di bagian bawah laptop, sehingga tidak ada aliran udara dingin yang terserap masuk. Selalu gunakan laptop di atas permukaan yang rata dan keras seperti meja.\n\n3. **Mengatur Opsi Power Management**\nAnda dapat mengurangi beban kerja CPU dengan membatasi performa maksimumnya saat tidak digunakan untuk tugas berat. Masuk ke Control Panel -> Power Options -> Change plan settings -> Advanced power settings -> Processor power management. Ubah **Maximum processor state** dari 100% menjadi 95% atau 90%. Ini akan menurunkan suhu CPU secara signifikan tanpa mengurangi performa yang terasa pada aplikasi perkantoran harian.",
                "excerpt" => "Tips mengatasi laptop yang cepat panas dan fan yang berisik.",
                "keywords" => "laptop overheating, fan berisik, cooling pad, thermal paste, compressed air, HWMonitor, power plan",
                'category_id' => $komputer->id,
            ],
            [
                "title" => "Cara Memilih Spesifikasi Komputer untuk Kebutuhan Kantor",
                "content" => "Pengadaan spesifikasi komputer kantor yang tidak tepat dapat menyebabkan pemborosan anggaran atau justru menghambat produktivitas karena spesifikasi yang terlalu rendah. Berikut adalah rekomendasi spesifikasi berdasarkan peran divisi kerja:\n\n1. **Divisi Administrasi, Customer Service, & Operasional (Standard)**\nUntuk tugas mengetik dokumen, input spreadsheet, dan browsing web, spesifikasi berikut sudah sangat mumpuni:\n- Prosesor: Intel Core i3 (Gen 12+) atau AMD Ryzen 3 (Gen 5000+)\n- RAM: 8 GB DDR4 (Minimal)\n- Storage: 256 GB / 512 GB SSD NVMe (Jangan gunakan HDD)\n- Layar: Monitor 19 - 21.5 inci Full HD\n\n2. **Divisi Akuntansi, Keuangan, & Analisis Data (Medium)**\nMemerlukan performa multitasking yang lebih kuat untuk mengolah data Excel berukuran besar secara simultan:\n- Prosesor: Intel Core i5 atau AMD Ryzen 5\n- RAM: 16 GB DDR4/DDR5\n- Storage: 512 GB SSD NVMe\n- Layar: Monitor Dual-Screen (sangat disarankan untuk mempermudah perbandingan data)\n\n3. **Divisi Desain Grafis, Video Editor, & IT Developer (High-End)**\nMembutuhkan performa rendering grafis dan kompilasi kode yang cepat:\n- Prosesor: Intel Core i7 atau AMD Ryzen 7\n- RAM: 32 GB DDR5\n- VGA/GPU: Dedicated Graphics Card (NVIDIA GeForce RTX 3060/4060 atau lebih tinggi)\n- Storage: 1 TB SSD NVMe + HDD 2 TB untuk arsip file\n- Layar: Monitor IPS 27 inci dengan akurasi warna tinggi (sRGB 99%+).",
                "excerpt" => "Panduan memilih spesifikasi komputer yang tepat untuk berbagai kebutuhan kantor.",
                "keywords" => "spesifikasi komputer, Intel i5, Intel i7, RAM 16GB, SSD, dedicated GPU, komputer kantor",
                'category_id' => $komputer->id,
            ],
            [
                'title' => 'Cara Backup dan Restore Data Windows dengan Windows Backup',
                'content' => "Pencadangan (backup) data secara teratur adalah satu-satunya perlindungan mutlak terhadap risiko kehilangan data akibat kerusakan harddisk fisik, bencana alam, pencurian laptop, atau serangan infeksi ransomware yang mengenkripsi file Anda. Berikut cara menyetel sistem backup otomatis di Windows:\n\n1. **Menyiapkan Media Penyimpanan Eksternal**\nSiapkan harddisk eksternal atau SSD portabel dengan kapasitas minimal dua kali lipat dari total ukuran data yang ingin Anda backup. Hubungkan drive tersebut ke port USB komputer.\n\n2. **Mengonfigurasi File History di Windows 10/11**\nBuka menu Start -> ketik **Settings** -> masuk ke **Update & Security** -> **Backup**. Klik tombol **Add a drive** dan pilih harddisk eksternal Anda. Aktifkan opsi 'Automatically back up my files'.\n\n3. **Menentukan Folder dan Jadwal Backup**\nKlik **More options** di bawah saklar File History. Di sini Anda dapat menentukan folder mana saja yang ingin dicadangkan (seperti folder Documents, Desktop, Pictures, dan folder khusus pekerjaan). Anda juga dapat mengatur frekuensi pencadangan, misalnya setiap jam, setiap hari, atau setiap minggu, serta menentukan berapa lama file backup akan disimpan sebelum dihapus otomatis.\n\n4. **Prosedur Restore Data yang Hilang**\nJika suatu hari file Anda terhapus atau rusak, buka kembali menu Backup Settings -> klik **More options** -> scroll ke bawah dan klik **Restore files from a current backup**. Anda dapat melihat riwayat folder berdasarkan tanggal, memilih versi file yang masih bagus, lalu klik tombol hijau di bagian bawah untuk mengembalikannya ke folder aslinya.",
                'excerpt' => 'Panduan setup backup dan restore data otomatis menggunakan Windows Backup.',
                'keywords' => 'backup Windows, restore data, Windows Backup, File History, external harddisk, scheduled backup',
                'category_id' => $komputer->id,
            ],
        ];

        // ============================================================
        // PRINTER (6 articles)
        // Domain: Printer errors, offline, not responding, printing issues
        // ============================================================
        $printerArticles = [
            [
                'title' => 'Cara Mengatasi Printer Offline dan Tidak Terdeteksi',
                'content' => "Printer yang berstatus offline atau tidak terdeteksi oleh sistem komputer dapat menghambat pekerjaan cetak dokumen penting. Masalah ini biasanya bersumber dari koneksi fisik, masalah spooler printer, atau driver yang tidak kompetibel. Ikuti langkah troubleshooting berikut untuk mengatasinya:\n\n1. **Memeriksa Koneksi Fisik & Kabel Data**\nPastikan printer dalam keadaan menyala dan tidak menunjukkan indikasi lampu error (seperti lampu berkedip orange/merah). Jika menggunakan kabel USB, pastikan kabel terpasang dengan erat di port printer maupun port komputer. Coba pindahkan kabel USB ke port lain di komputer Anda (pilih port USB bagian belakang jika menggunakan PC Desktop karena memiliki daya lebih stabil).\n\n2. **Memeriksa Status Offline pada Windows Settings**\nBuka Control Panel -> **Devices and Printers**. Klik kanan pada ikon printer Anda, lalu pilih **See what's printing**. Pada jendela baru yang muncul, klik menu **Printer** di pojok kiri atas, dan pastikan opsi **Use Printer Offline** tidak dalam kondisi tercentang. Jika tercentang, hilangkan centang tersebut.\n\n3. **Merestart Layanan Print Spooler**\nPrint Spooler adalah layanan sistem Windows yang bertugas mengelola semua dokumen yang dikirim ke printer. Jika layanan ini crash, printer akan terlihat offline. Tekan `Win + R`, ketik `services.msc` lalu tekan Enter. Cari layanan bernama **Print Spooler**, klik kanan, lalu pilih **Restart**.\n\n4. **Mengatasi Masalah IP Address untuk Printer Network (WiFi/LAN)**\nJika printer dihubungkan melalui jaringan, pastikan IP Address printer tidak berubah. Lakukan ping ke IP Address printer dari Command Prompt komputer Anda (misalnya `ping 192.168.1.200`). Jika membalas (Reply), berarti koneksi jaringan aman. Jika Request Timed Out, periksa status koneksi WiFi/kabel LAN pada printer Anda.",
                'excerpt' => 'Solusi lengkap mengatasi printer yang status offline dan tidak terdeteksi komputer.',
                'keywords' => 'printer offline, printer tidak terdeteksi, kabel USB, IP address printer, Print Spooler, driver printer',
                'category_id' => $printer->id,
            ],
            [
                'title' => 'Troubleshooting Printer Tidak Mau Ngeprint (No Response)',
                'content' => "Ketika Anda mengirim perintah cetak (print command) namun printer sama sekali tidak merespon tanpa memunculkan pesan error yang jelas di layar komputer, ikuti panduan pelacakan masalah berikut secara bertahap:\n\n1. **Memeriksa Antrean Dokumen yang Macet (Print Queue)**\nKerap kali dokumen yang gagal dicetak sebelumnya menghalangi dokumen baru untuk diproses. Buka Control Panel -> Devices and Printers -> klik kanan printer Anda -> pilih **See what's printing**. Klik menu **Printer** -> pilih **Cancel All Documents** untuk mengosongkan antrean cetak yang macet.\n\n2. **Memeriksa Kondisi Kertas dan Paper Jam Sensor**\nPastikan baki kertas (paper tray) terisi dengan kertas yang rapi dan tidak terlalu penuh. Terkadang sensor printer mendeteksi adanya kertas yang tersangkut atau habis, meskipun secara fisik baki terlihat normal. Tarik keluar baki kertas, pastikan kertas lurus, dorong kembali baki hingga terkunci rapat.\n\n3. **Melakukan Siklus Reset Printer**\nMatikan printer dengan menekan tombol Power. Cabut kabel listrik dari stopkontak dan kabel USB/LAN dari printer. Biarkan printer tanpa daya selama minimal 1 menit untuk mengosongkan memory buffer internal printer. Hubungkan kembali kabel dan nyalakan printer.\n\n4. **Menjalanakan Fitur Printer Self-Test Page**\nUntuk memastikan masalah bukan berasal dari sistem operasi Windows, Anda bisa melakukan uji cetak langsung dari perangkat keras printer (hardware test). Setiap printer memiliki kombinasi tombol tertentu untuk mencetak halaman uji tanpa komputer (misalnya, menahan tombol Resume/Paper selama beberapa detik hingga lampu berkedip, lalu lepaskan). Jika printer berhasil mencetak halaman uji mandiri, berarti masalahnya ada di komputer atau kabel data Anda.",
                'excerpt' => 'Cara mengatasi printer yang tidak merespon perintah print.',
                'keywords' => 'printer tidak ngeprint, printer no response, paper jam, tinta habis, print queue, test print',
                'category_id' => $printer->id,
            ],
            [
                'title' => 'Cara Mengatasi Hasil Print Bergaris atau Tidak Jelas',
                'content' => "Hasil cetakan yang bergaris-garis putih horizontal, warna pudar, atau teks yang buram menandakan adanya penyumbatan pada saluran tinta (nozzle) atau masalah pada drum toner. Berikut adalah panduan pemulihan kualitas cetak:\n\n1. **Untuk Printer Inkjet (Tinta Cair):**\n- **Nozzle Check**: Buka Control Panel -> Devices and Printers -> klik kanan printer -> **Printer Properties** -> masuk ke tab **Maintenance** -> klik **Nozzle Check**. Ini akan mencetak pola garis. Jika pola berlubang-lubang, nozzle tersumbat.\n- **Head Cleaning**: Pada tab Maintenance yang sama, klik **Head Cleaning**. Proses ini akan menyemprotkan tinta bertekanan tinggi untuk membersihkan print head dari tinta yang mengering. Ulangi hingga 2-3 kali.\n- **Power Ink Flushing (Deep Cleaning)**: Jika head cleaning biasa tidak berhasil, gunakan opsi **Deep Cleaning** atau **Power Ink Flushing**. Opsi ini mengonsumsi banyak tinta, gunakan hanya jika sangat diperlukan.\n\n2. **Untuk Printer Laser (Serbuk Toner):**\n- **Meratakan Serbuk Toner**: Lepaskan cartridge toner dari dalam printer. Goyangkan cartridge ke arah kiri dan kanan secara horizontal sebanyak 5-6 kali untuk meratakan serbuk toner di dalamnya yang mungkin menggumpal, lalu pasang kembali.\n- **Membersihkan Corona Wire**: Bersihkan kawat korona halus di dalam drum unit menggunakan tuas pembersih internal bawaan (biasanya berwarna hijau) atau gunakan cotton bud secara perlahan.\n- **Memeriksa Kondisi Drum OPC**: Jika hasil cetakan bergaris vertikal hitam pekat yang berulang, drum OPC silinder hijau kemungkinan telah tergores fisik dan harus diganti dengan unit baru.",
                'excerpt' => 'Solusi hasil print bergaris atau tidak jelas pada printer inkjet dan laser.',
                'keywords' => 'hasil print bergaris, print head cleaning, nozzle check, toner cartridge, drum unit, fuser',
                'category_id' => $printer->id,
            ],
            [
                'title' => 'Cara Mengatasi Kertas Macet (Paper Jam) di Printer',
                'content' => "Masalah kertas tersangkut atau *paper jam* di dalam mekanisme penarik printer adalah masalah mekanis yang paling sering terjadi. Sangat penting untuk mengeluarkan kertas dengan teknik yang benar agar tidak merusak sensor sensitif atau roda penarik (roller) di dalam printer:\n\n1. **Mematikan Printer Segera**\nMatikan printer dan cabut kabel daya dari stopkontak untuk menghindari kejutan listrik dan menghentikan pergerakan motor roda penarik yang sedang menjepit kertas.\n\n2. **Menarik Kertas Searah Jalur Keluar**\nBuka pintu akses belakang printer (jika tersedia) atau buka cover depan. Cari ujung kertas yang macet. **Tarik kertas secara perlahan menggunakan kedua tangan agar tekanan merata dan kertas tidak sobek.** Tarik kertas **searah dengan jalur keluar kertas**, jangan pernah menarik kertas berlawanan arah dengan jalur normal karena dapat mematahkan gigi roda gigi nilon di dalam printer.\n\n3. **Membersihkan Sobekan Kertas Kecil**\nJika kertas sobek saat ditarik, pastikan semua serpihan kertas kecil di dalam printer dikeluarkan dengan bantuan pinset atau senter. Serpihan kertas sekecil apapun yang menutupi sensor kertas akan membuat printer terus-menerus mendeteksi status *paper jam*.\n\n4. **Membersihkan Pickup Roller dari Debu Kertas**\nRoda karet penarik kertas (pickup roller) yang kotor oleh debu kertas akan menjadi licin dan gagal menarik kertas secara presisi, memicu status paper jam. Bersihkan permukaan karet roller menggunakan kain microfiber yang sedikit dibasahi dengan air bersih (jangan gunakan alkohol karena dapat merusak karet).",
                'excerpt' => 'Panduan lengkap mengatasi kertas macet di printer dengan aman.',
                'keywords' => 'kertas macet, paper jam, roller pickup, tray printer, jalur kertas, sobekan kertas',
                'category_id' => $printer->id,
            ],
            [
                'title' => 'Cara Install Driver Printer di Windows 10/11',
                'content' => "Sistem operasi Windows terbaru seringkali dapat mendeteksi printer baru secara otomatis, namun untuk mengaktifkan fitur pencetakan penuh (seperti scan dokumen resolusi tinggi, cetak bolak-balik, dan pemeliharaan nozzle), Anda harus menginstal driver resmi dari produsen printer tersebut. Berikut panduannya:\n\n1. **Mengunduh Driver Resmi dari Website Produsen**\nHindari menginstal driver dari CD bawaan karena versinya biasanya sudah usang. Buka Google dan cari dengan kata kunci '[Merk & Tipe Printer] Driver Download' (misalnya: `Epson L3210 Driver Download`). Pilih tautan resmi dari situs web produsen seperti Epson, Canon, HP, atau Brother. Pilih versi yang sesuai dengan sistem operasi Windows Anda (32-bit atau 64-bit).\n\n2. **Menjalankan Setup Installer**\nSetelah file instalasi berformat `.exe` selesai diunduh, klik kanan pada file tersebut dan pilih **Run as administrator**. Ikuti instruksi pada layar wizard instalasi.\n\n3. **Menghubungkan Kabel USB di Waktu yang Tepat**\n**PENTING**: Jangan hubungkan kabel USB printer ke komputer sebelum program installer meminta Anda melakukannya. Menghubungkan kabel terlalu cepat dapat membuat Windows mengasosiasikan printer dengan driver generik yang salah. Hubungkan kabel USB dan nyalakan printer saat diminta oleh wizard installer.\n\n4. **Menyetel Printer sebagai Default Device**\nSetelah instalasi selesai, buka Control Panel -> Devices and Printers. Klik kanan pada printer baru Anda, lalu pilih **Set as default printer**. Langkah ini memastikan semua perintah print dari aplikasi (Word, PDF, Browser) langsung mengarah ke printer tersebut.",
                'excerpt' => 'Panduan install driver printer di Windows 10/11 dengan benar.',
                'keywords' => 'install driver printer, driver HP, driver Canon, driver Epson, Windows 10, Windows 11, printer USB, printer network',
                'category_id' => $printer->id,
            ],
            [
                "title" => "Cara Setting Printer Network (LAN/WiFi) di Kantor",
                "content" => "Mengonfigurasi printer agar dapat diakses bersama (shared printer) oleh banyak pengguna di jaringan kantor melalui kabel LAN atau WiFi sangat meningkatkan efisiensi kerja. Berikut langkah-langkah konfigurasinya:\n\n1. **Menetapkan IP Address Statis pada Printer**\nIni adalah langkah paling krusial. Jika printer menggunakan IP dinamis (DHCP), IP printer akan berubah setiap kali printer atau router dinyalakan ulang, menyebabkan komputer klien kehilangan koneksi. Masuk ke menu pengaturan pada layar LCD printer -> Network Settings -> TCP/IP -> ubah dari DHCP menjadi **Static/Manual**. Masukkan IP Address di luar range DHCP router, misalnya `192.168.1.200`.\n\n2. **Menghubungkan Printer ke Jaringan**\nHubungkan printer menggunakan kabel ethernet LAN ke port switch terdekat, atau hubungkan ke SSID WiFi kantor melalui panel menu nirkabel printer.\n\n3. **Menambahkan Printer di Komputer Klien (Windows)**\nBuka Control Panel -> Devices and Printers -> klik tombol **Add a printer** di bagian atas. Jika Windows tidak mendeteksinya secara otomatis, klik link **The printer that I want isn't listed**.\n\n4. **Menghubungkan Melalui Alamat TCP/IP**\nPilih opsi **Add a printer using an IP address or hostname** -> klik Next. Pada kolom 'Device type', pilih 'TCP/IP Device'. Masukkan IP Address statis printer yang sudah diatur tadi (misal: `192.168.1.200`). Klik Next, Windows akan mengunduh driver dari database lokal atau meminta Anda mengarahkan ke folder driver yang sudah didownload sebelumnya.",
                "excerpt" => "Cara setting printer network/LAN untuk digunakan bersama di kantor.",
                "keywords" => "printer network, printer LAN, IP address static, TCP/IP, sharing printer, switch network",
                'category_id' => $printer->id,
            ],
        ];

        // ============================================================
        // EMAIL (6 articles)
        // Domain: Email issues, Gmail, Outlook, email configuration
        // ============================================================
        $emailArticles = [
            [
                "title" => "Cara Reset Password Email yang Lupa",
                "content" => "Lupa password email kantor atau email pribadi dapat sangat menghambat aktivitas kerja Anda. Berikut adalah prosedur standar keamanan untuk memulihkan dan mereset password email Anda dengan aman:\n\n1. **Menggunakan Fitur Recovery Email / No Telepon Pemulihan**\nBuka halaman login email provider Anda (seperti Gmail, Outlook, atau Yahoo). Masukkan alamat email Anda, lalu pada layar penginputan password, klik link **Forgot password?** atau **Lupa kata sandi**. Sistem akan menawarkan untuk mengirimkan kode verifikasi 6 digit ke alamat email pemulihan (recovery email) atau nomor telepon pemulihan yang telah Anda daftarkan sebelumnya.\n\n2. **Memasukkan Kode Verifikasi dengan Benar**\nPeriksa kotak masuk email pemulihan Anda (atau folder spam jika tidak kunjung masuk) atau periksa SMS pada ponsel Anda. Masukkan kode verifikasi yang diterima ke dalam form pemulihan di layar komputer Anda.\n\n3. **Membuat Password Baru yang Sangat Kuat**\nSetelah verifikasi berhasil, Anda akan diminta membuat password baru. Buatlah password yang memenuhi standar keamanan modern: minimal 12-16 karakter, mengombinasikan huruf kapital, huruf kecil, angka, dan simbol khusus (seperti `@`, `#`, `$`, `%`). Hindari menggunakan informasi pribadi seperti tanggal lahir, nama anak, atau kata umum yang mudah ditebak.\n\n4. **Menghubungi Administrator IT (Khusus Email Kantor/Domain Perusahaan)**\nJika akun email yang bermasalah adalah email institusi dengan domain perusahaan (misal: `karyawan@namaperusahaan.com`), Anda tidak dapat meresetnya sendiri jika tidak ada akses pemulihan mandiri. Hubungi tim Helpdesk IT internal Anda untuk melakukan reset password melalui konsol admin (seperti Google Workspace Admin Console atau Microsoft 365 Admin Center).",
                "excerpt" => "Panduan step by step reset password email yang lupa dengan mudah.",
                "keywords" => "reset password email, lupa password, forgot password, email recovery, two-factor authentication, password manager",
                'category_id' => $email->id,
            ],
            [
                "title" => "Mengatasi Email yang Tidak Bisa Dikirim (Stuck in Outbox)",
                "content" => "Masalah email yang tertahan di folder Outbox (kotak keluar) dan tidak mau terkirim sering dialami oleh pengguna aplikasi desktop mail client seperti Microsoft Outlook atau Mozilla Thunderbird. Berikut langkah-langkah mengatasinya:\n\n1. **Memeriksa Status Koneksi dan Mode Kerja Aplikasi**\nPeriksa pojok kanan bawah jendela aplikasi Outlook Anda. Pastikan status menunjukkan **Connected** atau **Online**. Jika statusnya menunjukkan **Disconnected** atau **Work Offline**, masuk ke tab **Send/Receive** di menu atas, lalu klik tombol **Work Offline** untuk mematikan mode offline tersebut dan menghubungkan kembali aplikasi ke server mail.\n\n2. **Memeriksa Ukuran Lampiran (Attachment Size Limit)**\nSetiap server email memiliki batas maksimal ukuran file lampiran yang diizinkan (biasanya 20MB hingga 25MB). Jika Anda melampirkan file video, presentasi, atau PDF berukuran besar, email tersebut akan gagal dikirim dan stuck di Outbox secara permanen. Solusinya: buka folder Outbox, klik kanan email yang stuck, pilih Delete. Upload file besar tersebut ke penyimpanan cloud (seperti Google Drive atau OneDrive) lalu kirimkan tautan/link unduhannya saja.\n\n3. **Memeriksa Pengaturan Autentikasi SMTP (Outgoing Server)**\nBuka Account Settings -> pilih akun email Anda -> klik Change -> klik More Settings -> masuk ke tab **Outgoing Server**. Pastikan opsi **My outgoing server (SMTP) requires authentication** telah dicentang, dan pilih opsi **Use same settings as my incoming mail server**. Tanpa autentikasi ini, server mail akan menolak pengiriman email Anda untuk mencegah penyebaran spam.",
                "excerpt" => "Solusi lengkap untuk email yang tidak bisa dikirim atau stuck di Outbox.",
                "keywords" => "email tidak bisa dikirim, stuck outbox, SMTP server, lampiran email, autentikasi SMTP, webmail",
                'category_id' => $email->id,
            ],
            [
                "title" => "Cara Setting Email di Outlook untuk Akun Kantor",
                "content" => "Mengonfigurasi email kantor menggunakan protokol IMAP atau Exchange di Microsoft Outlook adalah langkah pertama bagi karyawan baru untuk dapat mengakses komunikasi perusahaan. Berikut panduan setting manual secara detail:\n\n1. **Membuka Wizard Add Account**\nBuka Microsoft Outlook. Klik menu **File** di pojok kiri atas -> klik tombol **Add Account**. Masukkan alamat email kantor lengkap Anda.\n\n2. **Memilih Pengaturan Manual (Manual Setup)**\nCentang opsi **Let me set up my account manually** di bawah kolom email, kemudian klik Connect. Pilih tipe akun **IMAP** (sangat direkomendasikan karena menyinkronkan email di server, sehingga Anda dapat membukanya juga di HP tanpa kehilangan data).\n\n3. **Mengisi Detail Incoming & Outgoing Server**\nDapatkan informasi server mail dari tim IT Anda, kemudian isi kolom sebagai berikut:\n- **Incoming Mail Server**: biasanya `mail.namaperusahaan.com` atau `imap.secureserver.net` dengan port **993** dan tipe enkripsi **SSL/TLS**.\n- **Outgoing Mail Server (SMTP)**: biasanya `mail.namaperusahaan.com` atau `smtp.secureserver.net` dengan port **587** dan tipe enkripsi **STARTTLS** atau **TLS**.\n\n4. **Memasukkan Password dan Sinkronisasi**\nKlik Next, masukkan password email kantor Anda, lalu klik Connect. Outlook akan melakukan pengujian koneksi kirim dan terima (Send/Receive Test). Setelah sukses, Outlook akan mulai mengunduh seluruh folder email Anda dari server ke komputer lokal.",
                "excerpt" => "Panduan setting email kantor di Microsoft Outlook dengan konfigurasi IMAP/SMTP.",
                "keywords" => "setting email Outlook, email kantor, IMAP, SMTP, Office 365, AutoDiscover, incoming mail server",
                'category_id' => $email->id,
            ],
            [
                "title" => "Mengatasi Email Tidak Masuk ke Inbox (Gmail/Outlook)",
                "content" => "Ketika kolega Anda mengonfirmasi telah mengirimkan email namun Anda tidak melihat email tersebut di kotak masuk (Inbox), ikuti langkah-langkah pelacakan berikut untuk menemukan email tersebut:\n\n1. **Memeriksa Folder Spam / Junk Mail**\nIni adalah tempat pertama yang harus Anda periksa. Sistem filter email terkadang salah mengidentifikasi email penting (khususnya yang berisi lampiran, link luar, atau kata-kata promosi) sebagai spam. Jika email ditemukan di folder Spam, buka email tersebut lalu klik tombol **Not Spam** atau **Report as Not Junk** agar email dari pengirim tersebut di masa depan langsung masuk ke Inbox.\n\n2. **Memeriksa Tab Kategori Lain (Gmail)**\nJika menggunakan Gmail, periksa tab **Promotions**, **Social**, atau **Updates** di bagian atas kotak masuk. Google secara otomatis membagi email masuk berdasarkan jenisnya, dan email Anda mungkin terdistribusi ke sana.\n\n3. **Memeriksa Filter dan Block List Akun**\nMasuk ke Settings -> See all settings -> Filters and Blocked Addresses. Pastikan Anda tidak sengaja membuat aturan filter yang langsung menghapus (Delete) atau mengarsipkan (Archive) email dari domain tertentu. Cek juga daftar email yang diblokir.\n\n4. **Memeriksa Kapasitas Penyimpanan Akun**\nAkun Gmail gratis hanya menyediakan ruang 15GB (berbagi dengan Google Drive dan Google Photos). Jika penyimpanan Anda penuh (100%), semua email masuk baru akan ditolak oleh sistem dan pengirim akan menerima pesan error 'Mailbox is full'.",
                "excerpt" => "Solusi email yang tidak masuk ke inbox pada Gmail atau Outlook.",
                "keywords" => "email tidak masuk, inbox kosong, spam filter, folder promotions, kuota email penuh, email forwarding",
                'category_id' => $email->id,
            ],
            [
                "title" => "Cara Setting Email di Smartphone Android dan iPhone",
                "content" => "Menghubungkan email kantor ke smartphone pribadi (BYOD) sangat penting untuk menjaga mobilitas dan komunikasi yang responsif. Berikut cara konfigurasinya untuk perangkat Android dan iOS:\n\n1. **Untuk Perangkat Android (Menggunakan Aplikasi Gmail):**\n- Buka aplikasi Gmail -> ketuk foto profil Anda di pojok kanan atas -> pilih **Add another account**.\n- Pilih **Other** untuk email domain kustom kantor Anda.\n- Masukkan alamat email kantor dan klik **Manual Setup**.\n- Pilih **Personal (IMAP)**. Masukkan password email Anda.\n- Masukkan detail Server IMAP (misal: `imap.perusahaan.com`, port `993`, Security type `SSL/TLS`).\n- Masukkan detail Server SMTP (misal: `smtp.perusahaan.com`, port `587`, Security type `STARTTLS`). Klik Next dan tentukan frekuensi sinkronisasi.\n\n2. **Untuk Perangkat iPhone/iOS (Menggunakan Mail Bawaan):**\n- Buka menu Settings -> scroll ke bawah dan pilih **Mail** -> ketuk **Accounts** -> ketuk **Add Account**.\n- Pilih **Microsoft Exchange** (jika kantor Anda menggunakan Office 365) atau pilih **Other** -> **Add Mail Account** untuk IMAP biasa.\n- Masukkan Nama, Email, Password, dan deskripsi singkat.\n- Isi kolom Incoming Mail Server (Host Name, User Name, Password) dan Outgoing Mail Server (Host Name, User Name, Password).\n- Ketuk **Save** di pojok kanan atas untuk menyimpan dan memverifikasi akun.",
                "excerpt" => "Panduan lengkap setting email di smartphone Android dan iPhone.",
                "keywords" => "email smartphone, Android, iPhone, IMAP, SMTP, fetch new data, push email, Gmail app",
                'category_id' => $email->id,
            ],
            [
                "title" => "Cara Mengamankan Akun Email dari Peretasan",
                "content" => "Akun email adalah gerbang utama menuju identitas digital Anda, karena hampir semua platform online (seperti media sosial, e-commerce, hingga m-banking) menggunakan email untuk pemulihan password. Mengamankan email adalah prioritas keamanan siber tertinggi. Ikuti langkah pengamanan wajib berikut:\n\n1. **Mengaktifkan Otentikasi Dua Faktor (Two-Factor Authentication / 2FA)**\nIni adalah proteksi paling kuat. Dengan 2FA, meskipun peretas berhasil mengetahui password email Anda, mereka tetap tidak bisa login tanpa kode unik sekali pakai (OTP) yang dikirimkan ke ponsel Anda. Gunakan aplikasi authenticator seperti **Google Authenticator**, **Microsoft Authenticator**, atau **Authy** dibanding menggunakan OTP SMS yang rentan terhadap teknik *SIM Swap*.\n\n2. **Memeriksa Aktivitas Login Terkini (Login Activity)**\nSecara rutin (misal sebulan sekali), periksa riwayat login akun Anda. Di Gmail, Anda bisa klik link 'Details' di pojok kanan bawah kotak masuk. Di Outlook, buka account.microsoft.com -> Security -> **Sign-in activity**. Jika Anda melihat aktivitas login dari perangkat tidak dikenal atau lokasi negara lain yang tidak biasa, segera klik **Sign out of all other sessions** dan ganti password Anda saat itu juga.\n\n3. **Mewaspadai Phishing dan Cek URL Pengirim**\nJangan pernah memasukkan kredensial login email Anda pada halaman web yang dibuka melalui link di dalam email mencurigakan. Selalu pastikan domain pada address bar browser adalah alamat resmi penyedia email Anda sebelum melakukan login.",
                "excerpt" => "Strategi mengamankan akun email dari peretasan dan akses tidak sah.",
                "keywords" => "keamanan email, two-factor authentication, 2FA, password kuat, phishing, Google Authenticator, recovery email",
                'category_id' => $email->id,
            ],
        ];

        // ============================================================
        // KEAMANAN SISTEM (8 articles)
        // Domain: Ransomware, malware, virus, VPN, firewall, cybersecurity
        // ============================================================
        $securityArticles = [
            [
                'title' => 'Cara Mengatasi dan Mencegah Serangan Ransomware',
                'content' => "Ransomware adalah salah satu ancaman malware paling berbahaya bagi keamanan data perusahaan saat ini. Ransomware bekerja dengan menginfeksi sistem operasi, lalu mengenkripsi seluruh file dokumen penting secara senyap menggunakan kunci kriptografi tingkat tinggi, dan meminta tebusan uang kripto (Bitcoin/Monero) untuk mendapatkan kunci dekripsi. Berikut protokol penanganan dan pencegahan ransomware:\n\n1. **Tindakan Darurat Saat Terinfeksi (Isolasi Jaringan)**\nJika Anda melihat pesan tebusan (*ransom note*) di layar atau file Anda tiba-tiba berubah ekstensi menjadi aneh, **segera lepaskan kabel LAN dari komputer atau putuskan koneksi WiFi**. Isolasi fisik ini sangat krusial untuk menghentikan penyebaran ransomware ke komputer lain dalam satu jaringan lokal kantor atau ke server pusat data (Network Share/Shared Drive).\n\n2. **Jangan Membayar Tebusan**\nTim keamanan siber global dan penegak hukum sangat menyarankan untuk tidak membayar tebusan. Tidak ada jaminan bahwa pelaku akan memberikan kunci dekripsi yang valid, dan membayar tebusan hanya akan menandai instansi Anda sebagai target empuk yang menguntungkan bagi serangan di masa depan.\n\n3. **Mencari Decryptor Gratis (No More Ransom Project)**\nBeberapa varian ransomware lama atau yang kode pembuatannya cacat telah berhasil dipecahkan oleh peneliti keamanan. Kunjungi situs resmi **No More Ransom (nomoreransom.org)**. Anda dapat mengunggah sampel file yang terenkripsi untuk mendeteksi jenis ransomware dan mengunduh program *decryptor* resmi gratis jika tersedia.\n\n4. **Menerapkan Aturan Backup 3-2-1**\nSatu-satunya pertahanan mutlak terhadap ransomware adalah ketersediaan backup data yang steril. Terapkan strategi backup 3-2-1: simpan minimal **3 salinan data**, pada **2 media penyimpanan yang berbeda** (misal harddisk eksternal dan NAS), dan **1 salinan disimpan di luar lokasi (offsite/cloud storage)** yang terputus dari jaringan harian agar tidak ikut terenkripsi saat terjadi serangan.",
                'excerpt' => 'Panduan lengkap mengatasi dan mencegah serangan ransomware yang mengenkripsi file.',
                'keywords' => 'ransomware, malware enkripsi, decryptor, backup 3-2-1, isolasi komputer, No More Ransom, ID Ransomware',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Mengenali dan Menghapus Virus Komputer',
                'content' => "Virus komputer dan malware lainnya dapat merusak sistem operasi, mencuri data pribadi, dan merusak hardware jika dibiarkan aktif. Berikut adalah cara mengenali gejala infeksi virus dan langkah menghapusnya secara tuntas:\n\n1. **Gejala Umum Infeksi Virus**\n- Kinerja komputer menurun drastis secara tiba-tiba tanpa beban kerja tinggi.\n- Sering muncul jendela pop-up iklan yang tidak jelas, meskipun Anda sedang tidak membuka browser.\n- Beberapa file dokumen hilang secara acak atau berubah ekstensinya (misal menjadi `.exe` atau `.lnk`).\n- Program antivirus bawaan (Windows Defender) dinonaktifkan secara paksa oleh sistem dan tidak bisa diaktifkan kembali.\n- Task Manager atau Command Prompt tidak bisa dibuka karena diblokir oleh administrator sistem palsu.\n\n2. **Langkah Pembersihan Menggunakan Safe Mode**\nNyalakan ulang komputer Anda dan masuk ke **Safe Mode** (pada Windows, tekan tombol `Shift` saat mengklik tombol Restart, lalu pilih Troubleshoot -> Advanced Options -> Startup Settings -> Restart -> tekan tombol angka 4 atau F4). Safe Mode akan memuat sistem operasi hanya dengan driver paling dasar, mencegah virus otomatis berjalan di latar belakang.\n\n3. **Menjalankan Scan Windows Defender Offline**\nBeberapa malware canggih dapat menyembunyikan dirinya dari scan antivirus biasa saat Windows berjalan normal. Buka Settings -> Update & Security -> Windows Security -> Virus & threat protection -> Scan options -> centang **Microsoft Defender Offline scan** -> klik Scan now. Komputer akan merestart dan melakukan pemindaian menyeluruh sebelum sistem operasi Windows dimuat sepenuhnya.\n\n4. **Gunakan Antivirus Tambahan (Second Opinion Scanner)**\nUntuk memastikan sistem benar-benar bersih, instal program pembersih malware tambahan seperti **Malwarebytes Free** atau **AdwCleaner**. Jalankan pemindaian penuh untuk mendeteksi sisa-sisa adware, browser hijacker, atau trojan yang terlewat oleh antivirus utama.",
                'excerpt' => 'Cara mengenali gejala virus komputer dan langkah menghapusnya dengan tuntas.',
                'keywords' => 'virus komputer, malware, Windows Defender, Malwarebytes, Safe Mode, popup iklan, browser hijacker',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Perbedaan Malware, Virus, Trojan, dan Ransomware',
                'content' => "Dalam dunia keamanan informasi, istilah seperti malware, virus, trojan, dan ransomware sering digunakan secara bergantian oleh orang awam. Padahal, masing-masing memiliki karakteristik, cara penyebaran, dan dampak kerusakan yang sangat berbeda. Berikut penjelasannya:\n\n1. **Malware (Malicious Software)**\nMalware adalah istilah payung (*umbrella term*) yang mencakup **segala jenis perangkat lunak jahat** yang dirancang khusus untuk merusak komputer, mencuri data, atau mengganggu operasional sistem secara ilegal. Virus, trojan, dan ransomware adalah bagian dari kategori malware.\n\n2. **Virus Komputer**\nVirus adalah jenis malware yang memiliki kemampuan unik untuk **mereplikasi diri** dengan cara menyisipkan kode jahatnya ke dalam file atau program legal lain. Virus tidak dapat menyebar atau aktif tanpa adanya tindakan dari pengguna (*user interaction*), seperti menjalankan file `.exe` yang terinfeksi atau membuka lampiran email.\n\n3. **Trojan Horse**\nTrojan adalah malware yang menyamar sebagai perangkat lunak yang sah dan berguna (misalnya program utilitas sistem, game gratis, atau generator lisensi/crack). Setelah pengguna tertipu dan menginstalnya, Trojan akan membuka 'pintu belakang' (*backdoor*) di sistem Anda, memungkinkan peretas jarak jauh mengontrol komputer atau mengunduh malware lain secara diam-diam.\n\n4. **Ransomware**\nRansomware adalah jenis malware bermotif finansial yang sangat agresif. Ransomware tidak berfokus pada pencurian data secara diam-diam, melainkan langsung **mengunci akses file** milik korban dengan enkripsi kuat dan menampilkan instruksi pembayaran uang tebusan untuk memulihkannya.",
                'excerpt' => 'Memahami perbedaan jenis-jenis malware dan cara pencegahannya.',
                'keywords' => 'malware, virus, trojan, ransomware, worm, spyware, adware, rootkit, keylogger',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Mengaktifkan dan Konfigurasi Firewall Windows',
                'content' => "Firewall adalah sistem keamanan jaringan yang bertindak sebagai pos pemeriksaan atau filter pelindung antara komputer Anda dengan jaringan luar (seperti internet atau jaringan lokal kantor). Firewall menganalisis lalu lintas data masuk dan keluar berdasarkan aturan (*rules*) yang telah ditentukan guna memblokir koneksi berbahaya. Berikut cara mengonfigurasinya di Windows:\n\n1. **Memastikan Firewall Windows Defender Aktif**\nBuka menu Start -> ketik **Control Panel** -> pilih **System and Security** -> klik **Windows Defender Firewall**. Di panel sebelah kiri, pastikan status untuk jaringan Private networks maupun Guest or public networks berwarna hijau (On). Jika mati, klik **Turn Windows Defender Firewall on or off** dan ubah statusnya menjadi On.\n\n2. **Mengonfigurasi Aturan Masuk (Inbound Rules) & Keluar (Outbound Rules)**\nUntuk pengguna tingkat lanjut, Anda bisa mengontrol aplikasi mana saja yang diizinkan mengakses internet. Klik **Advanced settings** pada panel kiri Windows Defender Firewall. Jendela *Firewall with Advanced Security* akan terbuka.\n- **Inbound Rules**: Mengontrol lalu lintas data yang masuk ke komputer Anda dari luar. Berguna untuk memblokir port port tertentu yang rawan diserang peretas (seperti port 445 untuk file sharing SMB yang sering dieksploitasi malware).\n- **Outbound Rules**: Mengontrol lalu lintas data dari komputer Anda ke internet. Anda bisa memblokir aplikasi lokal mencurigakan agar tidak dapat mengirimkan data ke server luar.\n\n3. **Membuat Aturan Baru (New Rule) untuk Port Spesifik**\nJika Anda ingin memblokir atau mengizinkan port tertentu, klik kanan pada Inbound Rules -> pilih **New Rule** -> pilih opsi **Port** -> tentukan apakah TCP atau UDP, masukkan nomor port (misal port database `1433`) -> pilih **Block the connection** atau **Allow the connection** -> beri nama rule tersebut dan klik Finish.",
                'excerpt' => 'Panduan mengaktifkan dan mengkonfigurasi Firewall Windows Defender dengan benar.',
                'keywords' => 'firewall Windows, Windows Defender Firewall, inbound rules, outbound rules, network profile, Advanced settings',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Menggunakan VPN untuk Akses Jaringan Kantor yang Aman',
                'content' => "Dengan meningkatnya tren kerja remote (*work from home*), akses ke server data lokal kantor, aplikasi internal, atau printer jaringan dari rumah memerlukan jalur komunikasi yang aman. VPN (*Virtual Private Network*) membuat terowongan terenkripsi privat di atas jaringan publik internet untuk mengamankan data Anda. Berikut panduannya:\n\n1. **Mendapatkan Kredensial dan File Konfigurasi dari IT Helpdesk**\nSebelum melakukan koneksi, minta file konfigurasi VPN (biasanya berformat `.ovpn` atau instruksi server host) serta kredensial akun VPN Anda (username dan password unik) dari administrator jaringan kantor Anda.\n\n2. **Menginstal Aplikasi VPN Client**\nUnduh dan instal aplikasi VPN client resmi yang digunakan kantor Anda. Beberapa aplikasi VPN client yang paling umum digunakan untuk kebutuhan enterprise antara lain **OpenVPN Connect**, **Cisco AnyConnect**, **FortiClient**, atau **Mikrotik L2TP VPN** bawaan Windows.\n\n3. **Mengimpor Konfigurasi dan Melakukan Koneksi**\nBuka aplikasi VPN client Anda (misalnya OpenVPN). Pilih opsi **Import Profile** -> cari file `.ovpn` yang diberikan tim IT. Setelah terimport, masukkan username dan password Anda, centang opsi simpan password jika diinginkan, lalu klik tombol **Connect**.\n\n4. **Mengakses Jaringan Internal Kantor**\nSetelah status berubah menjadi 'Connected', laptop Anda secara virtual telah berada di dalam jaringan lokal kantor. Anda kini dapat membuka server file lokal dengan mengetikkan alamat IP internalnya (misalnya `\\192.168.10.5` di File Explorer) atau membuka aplikasi internal web kantor yang hanya bisa diakses menggunakan koneksi lokal.\n\n5. **Pentingnya Memutus Koneksi (Disconnect) Saat Selesai**\nDemi alasan keamanan dan hemat bandwidth kantor, selalu putuskan koneksi VPN (klik tombol **Disconnect**) segera setelah Anda selesai bekerja.",
                'excerpt' => 'Panduan menggunakan VPN untuk akses aman ke jaringan kantor dari remote.',
                'keywords' => 'VPN kantor, OpenVPN, Cisco AnyConnect, FortiClient, remote access, enkripsi traffic, jaringan internal',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Mengamankan Wifi dari Pencurian Sinyal dan Akses Ilegal',
                'content' => "Mengamankan WiFi kantor dari pencurian sinyal (freeloader) bukan hanya soal menghemat kuota internet, melainkan langkah vital untuk mencegah penyusup masuk ke dalam jaringan lokal perusahaan guna melakukan sniffing data. Berikut taktik keamanan nirkabel yang mendalam:\n\n1. **Menggunakan Standar Enkripsi Tertinggi (WPA3 / WPA2 Enterprise)**\nBuka halaman administrasi router Anda. Di bagian Security Mode, pastikan Anda menggunakan minimal **WPA2-PSK [AES]**. Jika router dan perangkat Anda sudah modern, aktifkan **WPA3-Personal** yang memiliki algoritma pertahanan yang jauh lebih kuat terhadap serangan brute force password. Untuk skala bisnis, gunakan autentikasi terpusat **WPA2-Enterprise** yang terhubung ke server RADIUS.\n\n2. **Menonaktifkan Fitur WPS (WiFi Protected Setup)**\nWPS adalah fitur yang memungkinkan perangkat terhubung ke WiFi secara cepat menggunakan tombol fisik atau PIN 8 digit. Masalahnya, PIN WPS sangat rentan terhadap serangan brute force menggunakan software peretas otomatis seperti *Reaver*. Cari menu WPS di admin panel router Anda, lalu ubah statusnya menjadi **Disabled**.\n\n3. **Membatasi Kekuatan Pancaran Sinyal (Transmit Power)**\nJika kantor Anda berada di ruko atau lantai gedung tertentu, Anda tidak ingin sinyal WiFi kantor terpancar kuat hingga ke tempat parkir luar atau jalan raya. Di admin panel router, masuk ke pengaturan Wireless Advanced -> cari opsi **Transmit Power** -> turunkan nilainya dari High menjadi Medium atau Low agar jangkauan sinyal terfokus hanya di dalam ruangan kantor saja.\n\n4. **Membuat Jaringan Khusus Tamu (Guest Network)**\nAktifkan fitur Guest Network di router Anda. Berikan password yang mudah diakses untuk tamu. Pastikan opsi 'Allow guests to access local network' **dinonaktifkan** agar para tamu tidak bisa mendeteksi atau terhubung dengan komputer kerja staf.",
                'excerpt' => 'Strategi lengkap mengamankan jaringan wifi dari pencurian sinyal dan akses ilegal.',
                'keywords' => 'keamanan wifi, WPA3, WPA2-AES, MAC address filtering, hide SSID, VLAN, WPS, RADIUS, 802.1X',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Mengaktifkan Windows Defender dan Antivirus Protection',
                'content' => "Windows Defender Antivirus adalah fitur keamanan bawaan sistem operasi Windows yang sangat andal dan ringan dalam mendeteksi malware secara real-time. Berikut cara mengaktifkan dan mengonfigurasinya untuk perlindungan maksimal:\n\n1. **Memeriksa Status Keaktifan Antivirus**\nKlik menu Start -> ketik **Windows Security** -> buka aplikasi tersebut. Pilih menu **Virus & threat protection**. Pastikan semua indikator bercentang hijau. Jika ada peringatan kuning atau merah, ikuti instruksi untuk mengaktifkan kembali layanannya.\n\n2. **Mengonfigurasi Fitur Real-Time Protection**\nDi bawah judul 'Virus & threat protection settings', klik **Manage settings**. Pastikan sakelar untuk opsi-opsi berikut berada dalam posisi **On**:\n- **Real-time protection**: Memindai file yang diunduh atau dijalankan secara instan untuk mencegah infeksi.\n- **Cloud-delivered protection**: Memberikan proteksi yang lebih cepat dengan memanfaatkan database ancaman terbaru di cloud Microsoft.\n- **Automatic sample submission**: Mengirimkan sampel file mencurigakan ke Microsoft untuk dianalisis guna meningkatkan keamanan global.\n\n3. **Mengaktifkan Fitur Controlled Folder Access (Ransomware Shield)**\nIni adalah perlindungan khusus terhadap ransomware. Pada menu Virus & threat protection, scroll ke bawah ke bagian **Ransomware protection** -> klik **Manage ransomware protection**. Aktifkan opsi **Controlled folder access**. Fitur ini akan memblokir aplikasi asing yang tidak terdaftar yang mencoba memodifikasi file di dalam folder penting Anda (seperti Documents, Pictures, Desktop).\n\n4. **Menambahkan Pengecualian (Exclusion) Jika Diperlukan**\nJika Anda memiliki aplikasi internal kantor yang sering salah terdeteksi sebagai virus (*false positive*), Anda dapat menambahkan folder aplikasi tersebut ke daftar pengecualian. Pada menu Manage Settings -> scroll ke bawah dan klik **Add or remove exclusions** -> klik Add an exclusion -> pilih Folder/File terkait.",
                'excerpt' => 'Cara mengaktifkan dan mengoptimalkan Windows Defender untuk perlindungan maksimal.',
                'keywords' => 'Windows Defender, antivirus, real-time protection, ransomware protection, controlled folder access, Full scan',
                'category_id' => $keamananSistem->id,
            ],
            [
                'title' => 'Cara Mengenali dan Menghindari Serangan Phishing',
                'content' => "Phishing adalah bentuk serangan siber di mana pelaku menyamar sebagai institusi tepercaya (seperti bank, admin IT kantor, atau penyedia layanan cloud) untuk menipu korban agar memberikan informasi sensitif, seperti username, password, pin, atau nomor kartu kredit. Berikut cara mendeteksi dan menghindarinya:\n\n1. **Memeriksa Alamat Email Pengirim Secara Detail**\nPeretas sering memalsukan nama tampilan (display name) email agar terlihat resmi. Jangan hanya membaca nama pengirimnya, melainkan klik alamat email tersebut untuk melihat alamat aslinya. Email resmi dari Google Workspace kantor Anda pasti berakhiran domain perusahaan Anda (misal `@kantor.com`), bukan domain umum seperti `@gmail.com` atau domain yang mirip tapi palsu (misal `@google-support-desk.net`).\n\n2. **Menganalisis Nada Bicara Email (Urgensi Tinggi)**\nEmail phishing hampir selalu menggunakan taktik intimidasi atau urgensi tinggi untuk membuat korban panik dan bertindak cepat tanpa berpikir jernih. Contoh kalimat: \"Akun Anda telah diretas, klik link ini dalam waktu 1 jam untuk mencegah penutupan akun permanen!\".\n\n3. **Melakukan Hover Link (Memeriksa URL Tujuan)**\nSebelum mengklik link apa pun di dalam email mencurigakan, layangkan kursor mouse Anda (*hover*) di atas link tersebut tanpa mengkliknya. Perhatikan alamat URL asli yang muncul di pojok kiri bawah layar browser Anda. Jika teks link tertulis `www.mybank.com` tetapi URL aslinya mengarah ke `www.hacker-site-login.ru`, itu adalah upaya penipuan phishing.\n\n4. **Jangan Mengunduh Lampiran Tanpa Konfirmasi**\nSerangan phishing sering menyertakan lampiran berbahaya yang menyamer sebagai 'Invoice Pembelian', 'Laporan Keuangan', atau 'Slip Gaji'. File ini biasanya berformat terkompresi (seperti `.zip`, `.rar`) atau ekstensi berbahaya lain seperti `.scr`, `.exe`, atau dokumen Word dengan macro aktif.",
                'excerpt' => 'Panduan mengenali ciri-ciri serangan phishing dan cara menghindarinya.',
                'keywords' => 'phishing, social engineering, email palsu, link mencurigakan, sertifikat SSL, two-factor authentication',
                'category_id' => $keamananSistem->id,
            ],
        ];

        // ============================================================
        // APLIKASI (6 articles)
        // Domain: Internal software, company applications, installation
        // ============================================================
        $aplikasiArticles = [
            [
                'title' => 'Cara Install Aplikasi Internal Perusahaan di Komputer Baru',
                'content' => "Sebagai karyawan baru atau saat Anda mendapatkan komputer inventaris kantor yang baru dideploy, Anda diharuskan menginstal rangkaian perangkat lunak operasional internal perusahaan. Ikuti panduan instalasi standar IT berikut:\n\n1. **Memperoleh Hak Akses Administrator**\nKebanyakan komputer inventaris kantor dikunci dengan hak akses terbatas untuk alasan keamanan. Pastikan Anda memiliki kredensial admin lokal (*Local Administrator*) atau hubungi teknisi IT Helpdesk untuk mendampingi instalasi guna mengizinkan hak akses tulis ke folder `C:\\Program Files`.\n\n2. **Mengunduh Installer dari Portal Intranet Resmi**\nJangan pernah menyalin installer aplikasi internal dari flashdisk rekan kerja karena rentan membawa virus atau merupakan versi lama yang sudah tidak kompatibel. Buka web browser, akses portal SharePoint internal perusahaan, masuk ke folder **IT Resources** -> **Approved Software**, lalu unduh installer aplikasi versi terbaru.\n\n3. **Menjalankan Setup Installer dengan Hak Admin**\nCari file installer berformat `.msi` atau `.exe` yang sudah diunduh. Klik kanan pada file tersebut dan pilih opsi **Run as administrator**. Ikuti instruksi pada wizard instalasi hingga selesai.\n\n4. **Menghubungkan Akun Active Directory (SSO)**\nSetelah aplikasi terpasang, buka aplikasi tersebut. Untuk login pertama kali, biasanya sistem sudah terintegrasi dengan metode Single Sign-On (SSO). Pilih opsi 'Sign in with Corporate Account' dan masukkan email serta password Windows kantor Anda yang terintegrasi dengan Active Directory.",
                'excerpt' => 'Panduan instalasi aplikasi internal perusahaan untuk karyawan baru.',
                'keywords' => 'install aplikasi internal, software perusahaan, Run as Administrator, Active Directory, LDAP, dependency',
                'category_id' => $aplikasi->id,
            ],
            [
                'title' => 'Troubleshooting Aplikasi Internal Tidak Bisa Login',
                'content' => "Mengalami kegagalan saat mencoba masuk (login) ke aplikasi internal kantor (seperti sistem ERP, CRM, atau Portal Kepegawaian) merupakan kendala operasional yang sering dilaporkan. Ikuti langkah troubleshooting berikut sebelum melaporkannya ke tim IT:\n\n1. **Memastikan Koneksi Jaringan yang Tepat (VPN Requirement)**\nSebagian besar aplikasi internal perusahaan dirancang untuk hanya dapat diakses dari dalam lingkungan jaringan fisik kantor. Jika Anda sedang bekerja secara remote dari rumah (WFH), pastikan Anda telah menyalakan dan menghubungkan koneksi **VPN Kantor** Anda terlebih dahulu. Tanpa VPN, koneksi aplikasi akan diblokir oleh firewall server kantor.\n\n2. **Memeriksa Status Akun Active Directory / LDAP**\nApakah password akun Windows Anda baru saja diganti? Atau apakah akun Anda mengalami lock-out karena salah memasukkan password sebanyak 3 kali berturut-turut? Jika demikian, Anda tidak akan bisa login ke aplikasi internal mana pun yang terintegrasi dengan sistem otentikasi AD/LDAP kantor. Hubungi IT Helpdesk untuk melakukan reset status lock-out akun Anda di server domain controller.\n\n3. **Membersihkan File Cache Aplikasi Lokal**\nData sesi login lama yang tersimpan dalam folder cache lokal dapat menjadi rusak (corrupted) dan menyebabkan aplikasi gagal merespon proses otentikasi. Bersihkan cache dengan menekan `Win + R`, ketik `%appdata%` -> cari folder dengan nama aplikasi tersebut -> hapus isi foldernya, kemudian buka kembali aplikasi Anda.",
                'excerpt' => 'Solusi lengkap untuk aplikasi internal yang tidak bisa login.',
                'keywords' => 'aplikasi internal, tidak bisa login, Active Directory, VPN, cache aplikasi, log error',
                'category_id' => $aplikasi->id,
            ],
            [
                'title' => 'Cara Update Aplikasi Internal ke Versi Terbaru',
                'content' => "Tim IT developer perusahaan secara berkala merilis pembaruan (*updates*) untuk aplikasi internal guna menambal celah keamanan, memperbaiki bug bug, dan menambahkan fitur baru. Berikut cara melakukan update aplikasi internal Anda secara aman:\n\n1. **Menutup Sesi Aplikasi Secara Sempurna**\nSebelum memulai proses update, pastikan aplikasi yang akan diperbarui telah ditutup sepenuhnya. Periksa juga di Task Manager (`Ctrl + Shift + Esc`) dan pastikan tidak ada proses latar belakang (*background processes*) dari aplikasi tersebut yang masih berjalan. Menjalankan installer saat file aplikasi sedang digunakan akan memicu error 'File in Use'.\n\n2. **Mengekspor Konfigurasi Penting (Backup)**\nUntuk menghindari kehilangan pengaturan kustom atau data lokal yang belum tersinkronisasi ke server, lakukan backup konfigurasi terlebih dahulu. Masuk ke menu Settings/Tools pada aplikasi -> pilih **Export Settings/Configuration**, lalu simpan file `.json` atau `.xml` cadangan tersebut di folder eksternal.\n\n3. **Mengunduh Patch / Installer Update**\nAkses portal unduhan IT perusahaan Anda, unduh file patch update terbaru. Jalankan file tersebut sebagai administrator. Installer akan secara otomatis mendeteksi folder instalasi aplikasi lama, menimpa file file lama dengan versi baru, dan melakukan registrasi ulang komponen sistem.\n\n4. **Melakukan Hard Refresh untuk Aplikasi Berbasis Web**\nJika aplikasi internal Anda berbasis web (web-app), pembaruan dilakukan di sisi server. Namun, browser Anda seringkali masih menyimpan cache file JavaScript versi lama. Lakukan hard refresh dengan menekan tombol **Ctrl + F5** di keyboard Anda saat membuka halaman web aplikasi untuk memuat kode JavaScript baru dari server.",
                'excerpt' => 'Panduan update aplikasi internal perusahaan ke versi terbaru dengan aman.',
                'keywords' => 'update aplikasi, upgrade software, release notes, backup konfigurasi, rollback, hard refresh',
                'category_id' => $aplikasi->id,
            ],
            [
                'title' => 'Cara Mengatasi Aplikasi Internal yang Sering Crash/Force Close',
                'content' => "Aplikasi internal yang mendadak tertutup sendiri (*force close*) atau memunculkan pesan error crash tanpa alasan yang jelas dapat disebabkan oleh konflik memori, kekurangan file dependensi, atau korupnya file instalasi. Ikuti langkah diagnosis berikut:\n\n1. **Memeriksa Log Error di Windows Event Viewer**\nWindows merekam semua detail kejadian sistem termasuk penyebab crash aplikasi. Tekan tombol Windows, ketik **Event Viewer**, masuk ke folder **Windows Logs** -> **Application**. Cari log dengan status 'Error' yang terjadi di waktu crash aplikasi Anda. Log ini akan menampilkan file modul mana yang menyebabkan crash (misalnya `.dll` tertentu), yang sangat membantu tim IT untuk mendiagnosis masalah.\n\n2. **Menginstal Ulang Dependensi Microsoft .NET Framework & Visual C++**\nAplikasi Windows buatan developer internal sangat bergantung pada pustaka runtime Microsoft. Kerusakan pada runtime ini sering memicu crash aplikasi. Unduh dan instal versi terbaru dari **Microsoft .NET Framework Runtime** serta **Visual C++ Redistributable (x86 & x64)** langsung dari situs web resmi Microsoft.\n\n3. **Menonaktifkan Mode Kompatibilitas**\nTergadang pengaturan kompatibilitas yang salah dapat menyebabkan crash. Klik kanan pada ikon pintasan (shortcut) aplikasi -> pilih Properties -> tab **Compatibility**. Pastikan opsi 'Run this program in compatibility mode for' tidak tercentang, kecuali jika aplikasi tersebut memang dirancang khusus untuk versi Windows lama.",
                'excerpt' => 'Solusi mengatasi aplikasi internal yang sering crash atau force close.',
                'keywords' => 'aplikasi crash, force close, Event Viewer, .NET Framework, Visual C++, compatibility mode, sfc scannow',
                'category_id' => $aplikasi->id,
            ],
            [
                'title' => 'Cara Setting Koneksi Database untuk Aplikasi Internal',
                'content' => "Aplikasi internal (seperti aplikasi pencatatan inventaris atau pelaporan harian) membutuhkan koneksi langsung ke server database terpusat agar data dapat tersimpan secara real-time. Jika Anda memindahkan aplikasi ke komputer baru atau server database kantor mengalami migrasi IP, Anda harus mengonfigurasi ulang parameter koneksinya:\n\n1. **Memahami Informasi Kredensial Database**\nDapatkan informasi parameter koneksi (*connection string*) berikut dari administrator database IT Anda:\n- **Database Host/IP Address**: Alamat IP server database (misal: `192.168.1.150` atau hostname `DBSERVER`).\n- **Port**: Port jaringan database (port default SQL Server adalah `1433`, MySQL `3306`, PostgreSQL `5432`).\n- **Database Name**: Nama database spesifik aplikasi.\n- **Authentication Credentials**: Username dan password khusus server database.\n\n2. **Mengedit File Konfigurasi Aplikasi**\nBuka folder instalasi aplikasi Anda. Cari file konfigurasi yang biasanya bernama `appsettings.json`, `web.config`, atau file berformat `.ini` / `.env`. Buka file tersebut menggunakan Notepad (jalankan Notepad sebagai admin terlebih dahulu). Ubah bagian `ConnectionStrings` dengan data IP, port, dan kredensial baru yang sudah didapatkan. Simpan file.\n\n3. **Menguji Koneksi Menggunakan Ping dan Telnet**\nJika aplikasi gagal terhubung, lakukan tes koneksi dasar. Buka Command Prompt, ketik `ping 192.168.1.150` untuk memastikan server menyala. Selanjutnya, tes apakah port database terbuka dengan perintah `telnet 192.168.1.150 1433` (jika fitur Telnet Client sudah diaktifkan di Windows Features).",
                'excerpt' => 'Panduan setting koneksi database untuk aplikasi internal perusahaan.',
                'keywords' => 'koneksi database, SQL Server, MySQL, connection string, Windows Authentication, firewall port',
                'category_id' => $aplikasi->id,
            ],
            [
                'title' => 'Cara Mengatasi Error "Missing DLL" pada Aplikasi Windows',
                'content' => "Error pesan 'The program can\'t start because MSVCP140.dll is missing from your computer' atau error sejenis yang menyebutkan file berekstensi `.dll` hilang adalah masalah umum di sistem operasi Windows. File DLL (*Dynamic Link Library*) adalah modul pustaka yang berisi sekumpulan fungsi dan prosedur yang dapat digunakan oleh program lain secara bersamaan. Berikut cara mengatasinya dengan aman:\n\n1. **Menginstal Paket Redistributable Resmi Microsoft**\nSebagian besar error DLL (terutama yang diawali dengan `msvcp`, `vcruntime`, atau `mfc`) disebabkan oleh tidak adanya paket **Visual C++ Redistributable** di komputer Anda. Jangan pernah mengunduh file DLL secara terpisah dari situs download pihak ketiga yang tidak resmi karena berisiko tinggi disisipi malware. Kunjungi situs resmi Microsoft, cari 'Visual C++ Redistributable Latest Supported Downloads', unduh dan instal paket untuk **x86** dan **x64** sekaligus.\n\n2. **Menjalankan Pemindaian System File Checker (SFC Scan)**\nJika file DLL yang hilang adalah bagian dari pustaka inti sistem operasi Windows, Anda dapat memulihkannya menggunakan pemindaian sistem otomatis. Buka Command Prompt sebagai Administrator, ketik perintah `sfc /scannow`, lalu tekan Enter. Windows akan memindai seluruh file sistem dan secara otomatis mengganti file DLL yang hilang atau korup dari salinan cadangan sistem.\n\n3. **Melakukan Re-registrasi File DLL Secara Manual**\nJika file DLL sudah ada di komputer Anda tetapi aplikasi masih memunculkan pesan error, Anda perlu meregistrasikan ulang file tersebut di Windows registry. Buka Command Prompt admin, ketik perintah `regsvr32 namafile.dll` (ganti `namafile.dll` dengan nama file yang bermasalah, lalu tekan Enter).",
                'excerpt' => 'Solusi lengkap mengatasi error missing DLL pada aplikasi Windows.',
                'keywords' => 'missing DLL, Visual C++ Redistributable, .NET Framework, sfc scannow, msvcp140, vcruntime, dependency',
                'category_id' => $aplikasi->id,
            ],
        ];

        // Combine all articles
        $allArticles = array_merge(
            $wifiArticles,
            $komputerArticles,
            $printerArticles,
            $emailArticles,
            $securityArticles,
            $aplikasiArticles
        );

        // Create each article with explicit category assignment
        foreach ($allArticles as $articleData) {
            // Generate slug from title
            $slug = Str::slug($articleData['title']);

            // Add index if slug already exists
            $originalSlug = $slug;
            $counter = 1;
            while (Article::where('slug', $slug)->exists()) {
                $slug = $originalSlug . '-' . $counter;
                $counter++;
            }

            Article::create([
                'category_id' => $articleData['category_id'],
                'staff_id' => $staffs->random()->id,
                'title' => $articleData['title'],
                'slug' => $slug,
                'content' => $articleData['content'],
                'excerpt' => $articleData['excerpt'],
                'keywords' => $articleData['keywords'],
                'views' => rand(50, 500),
                'is_published' => true,
                'is_hidden' => false,
                'publish_status' => 'approved',
                'created_at' => now()->subDays(rand(0, 90)),
                'updated_at' => now()->subDays(rand(0, 60)),
            ]);
        }
    }
}